urllib doesn't work with https under proxy
When access CSAR file which is URL and the protocol is https by proxy,
it will be error and the information is below:
toscaparser.common.exception.URLException: Failed to reach server
"https://raw.githubusercontent.com/openstack/tosca- parser/master/
toscaparser/tests/data/custom_types/wordpress.yaml". Reason is:
Tunnel connection failed: 503 Service Unavailable.

The reason of the error is urllib doesn't support https proxy and
the solution is using urllib2 instead of urllib.

closes-Bug: #1606015
Signed-off-by: shangxdy <shang.xiaodong@zte.com.cn>

Change-Id: I06cb2a33bfd02da7a5372c8162fdccad171e0edd